version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "xchange-frontend"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - mv package.json package.bak
            - npm install @types/lodash --no-save
            - npm install -g @angular/cli
            - mv package.bak package.json
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod
    post_build:
         commands:
            - aws s3 cp dist s3://xchange-frontend --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes